[WIP]Pretrained models
pfnet/pfrl pull request #33
Opened 2020-07-31 06:42 UTC by prabhatnagarajan

2020-07-31 06:44 UTC, prabhatnagarajan commented
DQN Performance comparison:

Network: Best

| Game        | PFRL Score           | Pretrained Demo Score |
| ------------- |:-------------:|:-------------:|
| AirRaid | **6020.3**| 5755.2|
| Alien | 1976.3| **2416.7**|
| Amidar | **976.6**| 176.9|
| Assault | 3542.6| **4428.6**|
| Asterix | 5715.3| **6061.7**|
| Asteroids | **1596.0**| 1407.4|
| Atlantis | 97512.8| **3781000.0**|
| BankHeist | 663.2| **664.4**|
| BattleZone | 5144.4| **11000.0**|
| BeamRider | 7146.6| **8066.0**|
| Berzerk | **658.8**| 498.9|
| Bowling | 55.5| 55.5|
| Boxing | **89.3**| 88.9|
| Breakout | **352.5**| 347.6|
| Carnival | 5249.2| **5614.8**|
| Centipede | 5058.7| **5648.1**|
| ChopperCommand | **4737.2**| 3500.0|
| CrazyClimber | **103234.4**| 99348.4|
| DemonAttack | 9208.2| **9227.7**|
| DoubleDunk | -10.9| **-10.0**|
| Enduro | 307.4| **788.7**|
| FishingDerby | **14.3**| 10.0|
| Freeway | 20.6| **30.6**|
| Frostbite | **1388.4**| 831.8|
| Gopher | 7947.2| **8907.7**|
| Gravitar | 471.9| **492.7**|
| Hero | 19588.2| **19945.5**|
| IceHockey | **-2.7**| -3.7|
| Jamesbond | **765.8**| 648.3|
| JourneyEscape | **-1713.3**| -1774.7|
| Kangaroo | **8345.6**| 7705.9|
| Krull | 5679.2| **7097.7**|
| KungFuMaster | 27362.2| **28609.5**|
| MontezumaRevenge | **0.6**| 0.0|
| MsPacman | **2776.4**| 2727.0|
| NameThisGame | 7279.9| **8659.1**|
| Phoenix | 9406.4| **9938.3**|
| Pitfall | **-4.7**| -5.8|
| Pong | **20.0**| 19.5|
| Pooyan | 3446.6| **3482.9**|
| PrivateEye | **2196.5**| 334.8|
| Qbert | 10675.1| **10785.6**|
| Riverraid | 7554.0| **7854.7**|
| RoadRunner | 36572.8| **37285.6**|
| Robotank | 47.5| **61.0**|
| Seaquest | **6252.0**| 6232.2|
| Skiing | **-12426.3**| -12934.0|
| Solaris | 1396.3| **5180.0**|
| SpaceInvaders | **1609.8**| 1516.9|
| StarGunner | **57293.9**| 56108.6|
| Tennis | -1.8| **0.0**|
| TimePilot | **5802.8**| 4909.6|
| Tutankham | **148.2**| 96.7|
| UpNDown | **11110.7**| 10255.9|
| Venture | **517.8**| 382.6|
| VideoPinball | **14376.7**| 10813.3|
| WizardOfWor | **2202.2**| 1173.3|
| YarsRevenge | 6602.9| **10898.7**|
| Zaxxon | 6191.1| **6573.1**|


DQN performance comparison

Network: final

| Game        | PFRL Score           | Pretrained Demo Score |
| ------------- |:-------------:|:-------------:|
| AirRaid | 2033.3| **5647.0**|
| Alien | 1641.9| **1768.8**|
| Amidar | **780.7**| 176.5|
| Assault | **1748.8**| 1481.3|
| Asterix | **856.5**| 106.7|
| Asteroids | 710.1| **1017.3**|
| Atlantis | **124120.1**| 46063.4|
| BankHeist | 495.1| **559.8**|
| BattleZone | **5693.8**| 3764.7|
| BeamRider | **8563.3**| 7585.0|
| Berzerk | 525.9| **798.2**|
| Bowling | **31.8**| 30.9|
| Boxing | 76.6| **80.1**|
| Breakout | 296.7| **297.8**|
| Carnival | 4825.1| **5012.4**|
| Centipede | **906.2**| 518.2|
| ChopperCommand | **3214.2**| 1933.3|
| CrazyClimber | 93779.0| **102579.2**|
| DemonAttack | **10979.3**| 10041.8|
| DoubleDunk | **-14.4**| -14.8|
| Enduro | 486.0| **518.4**|
| FishingDerby | -17.4| **-16.2**|
| Freeway | 19.9| **30.0**|
| Frostbite | **793.5**| 78.2|
| Gopher | **4309.8**| 3202.6|
| Gravitar | **382.7**| 179.5|
| Hero | 12359.2| **13817.7**|
| IceHockey | -9.9| **-7.9**|
| Jamesbond | 612.6| **860.2**|
| JourneyEscape | **-4079.3**| -6418.2|
| Kangaroo | 3487.5| **4448.8**|
| Krull | **5238.3**| 5122.8|
| KungFuMaster | **13000.3**| 9811.9|
| MontezumaRevenge | 0.0| 0.0|
| MsPacman | **2315.6**| 1822.8|
| NameThisGame | 6933.5| **7225.2**|
| Phoenix | 5500.8| **6946.4**|
| Pitfall | **-377.2**| -1139.0|
| Pong | **19.4**| 17.7|
| Pooyan | 2382.4| **2856.5**|
| PrivateEye | **-25.8**| -32.2|
| Qbert | **8511.3**| 3450.4|
| Riverraid | 3739.3| **6981.2**|
| RoadRunner | 25939.4| **37971.2**|
| Robotank | **59.0**| 54.9|
| Seaquest | 4528.7| **5918.7**|
| Skiing | -20050.9| **-13228.7**|
| Solaris | **1486.1**| 623.8|
| SpaceInvaders | **1226.7**| 841.1|
| StarGunner | **47830.9**| 19652.1|
| Tennis | -7.5| **-1.0**|
| TimePilot | **2676.6**| 1180.4|
| Tutankham | 70.1| **85.0**|
| UpNDown | **4126.0**| 3019.9|
| Venture | 293.3| **308.0**|
| VideoPinball | 10737.1| **12731.6**|
| WizardOfWor | **530.0**| 506.7|
| YarsRevenge | 2488.0| **4254.9**|
| Zaxxon | **2309.6**| 139.0|

2020-07-31 07:07 UTC, prabhatnagarajan commented
IQN Pretrained results
Network type: Final

| Game        | PFRL Score           | Pretrained Demo Score |
| ------------- |:-------------:|:-------------:|
| AirRaid | 7338.8| **8025.6**|
| Alien | 9100.4| **10094.6**|
| Amidar | **1640.3**| 430.7|
| Assault | **14819.4**| 13045.3|
| Asterix | **339089.7**| 221520.0|
| Asteroids | **2983.9**| 2199.4|
| Atlantis | **857325.0**| 806075.0|
| BankHeist | 1304.1| **1306.5**|
| BattleZone | **43454.2**| 35600.0|
| BeamRider | 23255.8| **27674.7**|
| Berzerk | **1450.2**| 972.1|
| Bowling | 53.0| **54.9**|
| Boxing | 99.5| **99.7**|
| Breakout | 512.3| **561.2**|
| Carnival | 4958.9| **5290.8**|
| Centipede | 9644.6| **10831.4**|
| ChopperCommand | **16908.3**| 13944.4|
| CrazyClimber | **157573.0**| 152523.1|
| DemonAttack | 126161.2| **130005.0**|
| DoubleDunk | **-5.0**| -11.8|
| Enduro | 1969.5| **2344.8**|
| FishingDerby | **32.5**| 15.2|
| Freeway | 33.9| **34.0**|
| Frostbite | **7051.8**| 6529.2|
| Gopher | 84830.0| **107576.0**|
| Gravitar | 927.3| **938.3**|
| Hero | **23287.0**| 20816.8|
| IceHockey | -0.5| **-0.2**|
| Jamesbond | 13345.7| **15166.7**|
| JourneyEscape | -952.4| **-744.1**|
| Kangaroo | 13673.5| **15025.0**|
| Krull | **9000.7**| 8948.9|
| KungFuMaster | **57625.3**| 51914.3|
| MontezumaRevenge | 0.0| 0.0|
| MsPacman | **4080.1**| 3729.4|
| NameThisGame | **21118.1**| 19180.0|
| Phoenix | **77939.7**| 75497.1|
| Pitfall | -5.6| **-4.2**|
| Pong | **20.9**| 20.8|
| Pooyan | **8904.0**| 8774.3|
| PrivateEye | **259.2**| 195.7|
| Qbert | **23606.3**| 20837.7|
| Riverraid | 19020.6| **23351.2**|
| RoadRunner | 62138.5| **65831.2**|
| Robotank | **69.7**| 63.5|
| Seaquest | **14851.7**| 11770.9|
| Skiing | **-29530.2**| -29969.9|
| Solaris | 2822.2| **4617.5**|
| SpaceInvaders | 15537.1| **28490.6**|
| StarGunner | **158305.8**| 131047.1|
| Tennis | **23.1**| 22.0|
| TimePilot | 10456.6| **11528.3**|
| Tutankham | **211.2**| 150.6|
| UpNDown | **15195.9**| 8106.9|
| Venture | **523.1**| 0.0|
| VideoPinball | 409003.1| **542410.0**|
| WizardOfWor | **17402.3**| 13893.9|
| YarsRevenge | **27230.7**| 25386.0|
| Zaxxon | 15215.2| **16125.0**|

2020-08-06 04:50 UTC, prabhatnagarajan commented
Rainbow Pretrained Results
Pretrained type: Best

| Game        | PFRL Score           | Pretrained Demo Score |
| ------------- |:-------------:|:-------------:|
| AirRaid | **6616.1**| 5370.2|
| Alien | **10255.4**| 8576.5|
| Amidar | **4284.6**| 839.2|
| Assault | **15331.9**| 12741.3|
| Asterix | 550307.6| **919625.0**|
| Asteroids | **3399.6**| 2909.7|
| Atlantis | **883073.0**| 872250.0|
| BankHeist | 1272.7| **1624.4**|
| BattleZone | **202382.5**| 195055.6|
| BeamRider | 21661.5| **31980.0**|
| Berzerk | **6018.1**| 4152.2|
| Bowling | 62.3| **66.0**|
| Boxing | **99.9**| 84.4|
| Breakout | **317.8**| 312.6|
| Carnival | **5687.1**| 5678.1|
| Centipede | 7546.8| **8203.1**|
| ChopperCommand | 21014.5| **26086.7**|
| CrazyClimber | **174025.0**| 152188.0|
| DemonAttack | **100980.6**| 96993.8|
| DoubleDunk | **-0.1**| -1.0|
| Enduro | 2281.9| **2340.0**|
| FishingDerby | **39.1**| 19.6|
| Freeway | **33.6**| 33.4|
| Frostbite | **11046.3**| 10175.0|
| Gopher | **76872.9**| 56640.0|
| Gravitar | **1387.2**| 1252.9|
| Hero | **34234.5**| 33752.8|
| IceHockey | 6.6| **8.4**|
| Jamesbond | **23222.9**| 22265.0|
| JourneyEscape | -184.8| **-47.6**|
| Kangaroo | 13726.5| **14967.7**|
| Krull | 7844.4| **7910.2**|
| KungFuMaster | 54835.5| **58505.3**|
| MontezumaRevenge | 21.0| **114.3**|
| MsPacman | 5277.3| **5391.8**|
| NameThisGame | **14679.0**| 14341.9|
| Phoenix | **147467.9**| 1922.7|
| Pitfall | -3.4| **0.0**|
| Pong | 21.0| 21.0|
| Pooyan | 15040.2| **22213.3**|
| PrivateEye | **101.7**| 100.0|
| Qbert | **42518.7**| 41747.6|
| Riverraid | 30121.2| **30996.1**|
| RoadRunner | **67638.5**| 59350.0|
| Robotank | **74.0**| 73.6|
| Seaquest | **5277.4**| 4716.7|
| Skiing | -29974.7| **-29969.9**|
| Solaris | **6730.1**| 3672.3|
| SpaceInvaders | **2823.1**| 2616.2|
| StarGunner | **155248.8**| 118250.0|
| Tennis | -0.1| **0.0**|
| TimePilot | 24038.2| **26541.7**|
| Tutankham | **258.0**| 244.0|
| UpNDown | **258505.5**| 136196.2|
| Venture | **2.5**| 0.0|
| VideoPinball | **292835.7**| 101324.4|
| WizardOfWor | **21341.2**| 16289.7|
| YarsRevenge | 93877.2| **104410.4**|
| Zaxxon | **25084.0**| 23766.7|

| Results Summary ||
| ------------- |:-------------:|
| Number of common domains | 59 |
| Number of domains where paper scores higher | 21 |
| Number of domains where PFRL scores higher | 37 |
| Number of ties between paper and PFRL | 1 |

2020-09-07 06:54 UTC, prabhatnagarajan commented
PPO Pretrained results
Pretrained type: Final

| Env        | PFRL Score           | Pretrained Demo Score |
| ------------- |:-------------:|:-------------:|
| HalfCheetah | 1986 | **2848.4** |
| Hopper | 2793 | **2907.4** |
| Walker2d | **2873** | 953.4 |
| Swimmer | **125** | 112.6 |

2020-09-08 06:01 UTC, prabhatnagarajan commented
SAC Pretrained results
Pretrained type: Best

| Environment               | PFRL Score | Pretrained Demo Score |
| ------------------------- |:----------:|:--------------:|
| Hopper-v2                 |    3279.25 | **3659.9** |
| HalfCheetah-v2            |  15120.03 |  **15864.1** |
| Walker2d-v2               |    4875.88 | **6503.7** |
| Ant-v2                    |    5953.15 | **6434.7** |
| Humanoid-v2               |    7939.08 | **8345.4** |

2020-09-08 06:56 UTC, prabhatnagarajan commented
TRPO Pretrained results
Pretrained type: Best

| Environment | PFRL Score | Pretrained Demo Score |
| ----------- |:---------------:|:--------------:|
| HalfCheetah |  **1561**+/-114 |  1122.1  |
| Hopper      |   **3038**+/-42 |   3001.0   |
| Walker2d    |       3260+/-82 | 3094.9 |
| Swimmer     |        197+/-26 |  103.2  |

TRPO Pretrained results
Pretrained type: Final

| Environment | PFRL Score | Pretrained Demo Score |
| ----------- |:---------------:|:--------------:|
| HalfCheetah |  **1561**+/-114 | 1126.5 |
| Hopper      |   3038+/-42 |  **3065.5**  |
| Walker2d    |       3260+/-82 | 2919.7 |
| Swimmer     |        197+/-26 |  103.2 |

2020-09-08 09:10 UTC, prabhatnagarajan commented
TD3 Pretrained results
Pretrained type: Best

| Environment               | PFRL Final Avg Score   | Pretrained Demo Score |
| ------------------------- |:------------:|:--------------:|
| HalfCheetah-v2            | 10047.79 |  **10831.2**   |
| Hopper-v2                 |  3400.06 |  **3698.4**  |
| Walker2d-v2               |      4056.17 |  |
| Ant-v2                    |  4333.70 |    **5100.3**  |
| Reacher-v2                |        -3.87 |     **-3.75**     |
| InvertedPendulum-v2       |       964.92 |  **1000.0**   |
| InvertedDoublePendulum-v2 |      7216.69 | **9356.4**    |

TD3 Pretrained results
Pretrained type: Final


| Environment               | PFRL Final Avg Score   | Pretrained Demo Score |
| ------------------------- |:------------:|:--------------:|
| HalfCheetah-v2            | 10047.79 |   **10307.14**  |
| Hopper-v2                 |  3400.06 |     **3593.6**    |
| Walker2d-v2               |      4056.17 |     |
| Ant-v2                    |  4333.70 |     **5045.26**    |
| Reacher-v2                |        -3.87 |   **-3.8**  |
| InvertedPendulum-v2       |       964.92 |  **1000.0**  |
| InvertedDoublePendulum-v2 |      7216.69 |   **9354.7**  |

2020-09-15 11:53 UTC, prabhatnagarajan commented
A3C Results
Network type final

| Game        | PFRL Score           | Original Reported Scores |
| ------------- |:-------------:|:-------------:|
| Adventure | N/A| -0.8|
| AirRaid | 4703.2| **4740.32156368222**|
| Alien | **2830.6**| 1588.9483727637792|
| Amidar | 296.3| **758.308245169715**|
| Assault | **5440.0**| 5330.0136636636635|
| Asterix | 5907.9| **9523.824257425742**|
| Asteroids | 1716.8| **2571.1170737300768**|
| Atlantis | **879125.0**| 857841.6666666666|
| BankHeist | 1291.6| **1296.1290322580646**|
| BattleZone | **13365.9**| 9536.695441288854|
| BeamRider | **8303.0**| 7607.023188405798|
| Berzerk | **846.1**| 835.7010097112355|
| Bowling | 29.6| **30.419540229885058**|
| Boxing | 90.9| **97.14818438603903**|
| Breakout | **536.4**| 503.7701034367701|
| Carnival | 4445.8| **5017.441969612481**|
| Centipede | **4537.1**| 4453.95615729313|
| ChopperCommand | 3459.5| **5428.621753108643**|
| CrazyClimber | 109278.1| **110251.64650537634**|
| Defender | N/A| 574095.2|
| DemonAttack | **74410.8**| 71101.20833333333|
| DoubleDunk | -2.5| **0.3333333333333333**|
| ElevatorAction | N/A| 12850.0|
| Enduro | 0.0| 0.0|
| FishingDerby | 25.7| **37.10737490335445**|
| Freeway | 0.0| 0.0|
| Frostbite | **302.6**| 293.0205996245313|
| Gopher | **7376.2**| 7008.241750033347|
| Gravitar | 181.2| **186.56717375725495**|
| Hero | 196.0| **23223.540900058444**|
| IceHockey | **-6.5**| -6.717948717948718|
| Jamesbond | **282.5**| 271.7443493432457|
| JourneyEscape | **-1118.8**| -1274.7058823529412|
| Kangaroo | 54.1| **55.156100648428016**|
| Krull | **9749.3**| 9618.79975709423|
| KungFuMaster | 28506.7| **29926.844642195032**|
| MontezumaRevenge | 0.0| 0.0|
| MsPacman | 2292.6| **2568.8708412252004**|
| NameThisGame | **11196.5**| 8086.446398046399|
| Phoenix | **36051.7**| 31102.795414462078|
| Pitfall | **-5.0**| -10.485644592765338|
| Pong | **20.8**| 20.762549829673116|
| Pooyan | **3871.6**| 3713.3342293906812|
| PrivateEye | **100.0**| 92.7536231884058|
| Qbert | **19693.0**| 19639.529585419074|
| Riverraid | **13720.4**| 13304.436628186626|
| RoadRunner | 34986.7| **35617.80664367224**|
| Robotank | **2.5**| 2.2788888888888894|
| Seaquest | **1755.6**| 1752.909090909091|
| Skiing | -16338.7| **-16184.294436739097**|
| Solaris | 2365.6| **2474.014447884417**|
| SpaceInvaders | 826.6| **939.0923210660053**|
| StarGunner | **52707.5**| 52615.84323535543|
| Tennis | -13.1| **-10.055555555555555**|
| TimePilot | 4898.0| **4992.615686233408**|
| Tutankham | **309.6**| 296.0844226579521|
| UpNDown | 29491.9| **40755.24886877828**|
| Venture | 0.0| 0.0|
| VideoPinball | 71393.4| **135225.00374621394**|
| WizardOfWor | **3096.4**| 2801.5187445510032|
| YarsRevenge | **25541.2**| 20691.23239868786|
| Zaxxon | 13.6| **14.440820014795618**|

| Results Summary ||
| ------------- |:-------------:|
| Reporting Protocol | The final evaluation score |
| Number of common domains | 59 |
| Number of domains where Demo scores higher | 26 |
| Number of domains where PFRL scores higher | 29 |
| Number of ties between demo and PFRL | 4 |

2020-09-15 12:19 UTC, prabhatnagarajan commented
Algorithm: Rainbow
Network: Best

| Game        | PFRL Score           | Demo Scores |
| ------------- |:-------------:|:-------------:|
| AirRaid | 5370.2| **6616.1**|
| Alien | 8576.5| **10255.4**|
| Amidar | 839.2| **4284.6**|
| Assault | 12741.3| **15331.9**|
| Asterix | **919625.0**| 550307.6|
| Asteroids | 2909.7| **3399.6**|
| Atlantis | 872250.0| **883073.0**|
| BankHeist | **1624.4**| 1272.7|
| BattleZone | 195055.6| **202382.5**|
| BeamRider | **31980.0**| 21661.5|
| Berzerk | 4152.2| **6018.1**|
| Bowling | **66.0**| 62.3|
| Boxing | 84.4| **99.9**|
| Breakout | 312.6| **317.8**|
| Carnival | 5678.1| **5687.1**|
| Centipede | **8203.1**| 7546.8|
| ChopperCommand | **26086.7**| 21014.5|
| CrazyClimber | 152188.0| **174025.0**|
| DemonAttack | 96993.8| **100980.6**|
| DoubleDunk | -1.0| **-0.1**|
| Enduro | **2340.0**| 2281.9|
| FishingDerby | 19.6| **39.1**|
| Freeway | 33.4| **33.6**|
| Frostbite | 10175.0| **11046.3**|
| Gopher | 56640.0| **76872.9**|
| Gravitar | 1252.9| **1387.2**|
| Hero | 33752.8| **34234.5**|
| IceHockey | **8.4**| 6.6|
| Jamesbond | 22265.0| **23222.9**|
| JourneyEscape | **-47.6**| -184.8|
| Kangaroo | **14967.7**| 13726.5|
| Krull | **7910.2**| 7844.4|
| KungFuMaster | **58505.3**| 54835.5|
| MontezumaRevenge | **114.3**| 21.0|
| MsPacman | **5391.8**| 5277.3|
| NameThisGame | 14341.9| **14679.0**|
| Phoenix | 1922.7| **147467.9**|
| Pitfall | **0.0**| -3.4|
| Pong | **21.0**| 21.0|
| Pooyan | **22213.3**| 15040.2|
| PrivateEye | 100.0| **101.7**|
| Qbert | 41747.6| **42518.7**|
| Riverraid | **30996.1**| 30121.2|
| RoadRunner | 59350.0| **67638.5**|
| Robotank | 73.6| **74.0**|
| Seaquest | 4716.7| **5277.4**|
| Skiing | **-29969.9**| -29974.7|
| Solaris | 3672.3| **6730.1**|
| SpaceInvaders | 2616.2| **2823.1**|
| StarGunner | 118250.0| **155248.8**|
| Tennis | **0.0**| -0.1|
| TimePilot | **26541.7**| 24038.2|
| Tutankham | 244.0| **258.0**|
| UpNDown | 136196.2| **258505.5**|
| Venture | 0.0| **2.5**|
| VideoPinball | 101324.4| **292835.7**|
| WizardOfWor | 16289.7| **21341.2**|
| YarsRevenge | **104410.4**| 93877.2|
| Zaxxon | 23766.7| **25084.0**|

| Results Summary ||
| ------------- |:-------------:|
| Reporting Protocol | A re-evaluation of the best intermediate agent |
| Number of common domains | 59 |
| Number of domains where Demo scores higher | 37 |
| Number of domains where PFRL scores higher | 22 |
| Number of ties between demo and PFRL | 0 | 


Algorithm:Rainbow
Network Type: Final

| Game        | PFRL Score           | Demo Scores |
| ------------- |:-------------:|:-------------:|
| AirRaid | 2888.9| **5317.0**|
| Alien | 9361.3| **9504.7**|
| Amidar | 485.9| **3353.9**|
| Assault | **19303.8**| 11801.0|
| Asterix | 397800.0| **419731.2**|
| Asteroids | 1938.9| **2500.9**|
| Atlantis | 835100.0| **842312.5**|
| BankHeist | **1624.8**| 1273.7|
| BattleZone | 120800.0| **211428.6**|
| BeamRider | **23610.5**| 19132.9|
| Berzerk | **6189.7**| 5345.3|
| Bowling | **30.0**| 28.9|
| Boxing | 58.7| **100.0**|
| Breakout | **350.8**| 328.8|
| Carnival | **5691.3**| 5605.5|
| Centipede | 7806.2| **8117.8**|
| ChopperCommand | **26086.7**| 20166.6|
| CrazyClimber | 153952.0| **161786.1**|
| DemonAttack | 81862.0| **85859.0**|
| DoubleDunk | -1.0| **0.0**|
| Enduro | 2340.0| **2341.1**|
| FishingDerby | 13.7| **34.2**|
| Freeway | 33.2| **33.6**|
| Frostbite | **10565.8**| 10140.1|
| Gopher | **64177.1**| 48135.4|
| Gravitar | 1216.9| **1387.3**|
| Hero | 33730.6| **34126.8**|
| IceHockey | **7.5**| 7.1|
| Jamesbond | 19130.8| **23410.0**|
| JourneyEscape | -607.6| **-515.9**|
| Kangaroo | **14987.1**| 13487.3|
| Krull | 7883.8| **7885.8**|
| KungFuMaster | **56826.3**| 54149.4|
| MontezumaRevenge | 0.0| 0.0|
| MsPacman | 5002.2| **5222.6**|
| NameThisGame | **14052.2**| 14017.5|
| Phoenix | 1512.1| **118361.2**|
| Pitfall | -7.1| **-5.0**|
| Pong | 21.0| 21.0|
| Pooyan | **8925.2**| 7493.3|
| PrivateEye | 100.0| 100.0|
| Qbert | **40510.9**| 40141.9|
| Riverraid | 27469.8| **27671.6**|
| RoadRunner | 58747.5| **68055.5**|
| Robotank | 72.9| **74.0**|
| Seaquest | 4608.4| **5244.2**|
| Skiing | **-29969.9**| -29977.6|
| Solaris | 1907.3| **2178.8**|
| SpaceInvaders | 2174.1| **2877.9**|
| StarGunner | 118250.0| **162496.6**|
| Tennis | 0.0| 0.0|
| TimePilot | **25780.6**| 22690.8|
| Tutankham | 247.3| **264.0**|
| UpNDown | 141508.3| **274730.0**|
| Venture | 0.0| 0.0|
| VideoPinball | 73897.8| **422753.4**|
| WizardOfWor | 12796.7| **20622.8**|
| YarsRevenge | **100727.8**| 87608.0|
| Zaxxon | 17993.5| **23161.7**|

| Results Summary ||
| ------------- |:-------------:|
| Reporting Protocol | The final evaluation score |
| Number of common domains | 59 |
| Number of domains where Demo scores higher | 35 |
| Number of domains where PFRL scores higher | 19 |
| Number of ties between demo and PFRL | 5 |

2020-12-10 15:40 UTC, prabhatnagarajan commented
/test

2020-12-10 16:24 UTC, prabhatnagarajan commented
Algorithm: DDPG
Final network

| **Environment**               | **PFRL Score**  | **Pretrained Score** |
| ------------------------- |:-----------:|:--------------:|
| HalfCheetah-v2            | **9750.57** | 8625.39 |
| Hopper-v2                 | 1577.20 | **3459.48** |
| Walker2d-v2               |     **2098.46** | 1909.11 |
| Ant-v2                    |  753.00 | **847.16** |
| Reacher-v2                |       -5.64 | **-5.05** |
| InvertedPendulum-v2       |      **844.17** | 106.3 |
| InvertedDoublePendulum-v2 |     6464.58 | **9201.52** |

2020-12-10 16:46 UTC, prabhatnagarajan commented
/test

2020-12-11 05:31 UTC, prabhatnagarajan commented
/test

2020-12-11 07:28 UTC, prabhatnagarajan commented
/test

2020-12-14 09:51 UTC, muupan commented
Why is TD3's Walker2d-v2 result blank?

2020-12-14 09:56 UTC, prabhatnagarajan commented
Not sure, I ran these results individually so I must have overlooked it. I just ran those pretrained models and updated the results.

2020-12-16 02:52 UTC, muupan requested changes

2020-12-16 04:56 UTC, prabhatnagarajan commented
/test

2020-12-16 11:08 UTC, muupan approved these changes

2020-12-16 11:08 UTC, merged