add use_shared_memory option
pfnet/pfrl pull request #56
Opened 2020-09-03 01:58 UTC by shu65

This PR adds `use_shared_memory` to share data among agents.
When I try to another method to share data, I got errors.

To solve it,  I would like to add the option in `train_agent_async()`

2021-01-04 05:28 UTC, prabhatnagarajan commented
/test

2021-01-04 05:35 UTC, prabhatnagarajan requested changes

2021-01-04 05:35 UTC, prabhatnagarajan commented on pfrl/experiments/train_agent_async.py
> +        use_shared_memory (bool): Prevent using shared memory.
```suggestion
        use_shared_memory (bool): Share memory amongst asynchronous agents.
```
If true, then share memory, right? So we shouldn't say "Prevent"?

2021-03-30 06:56 UTC, shu65 commented
Thank you for the comments. I fixed the docstring.

2021-06-23 02:24 UTC, muupan commented
/test

2021-06-23 02:44 UTC, muupan approved these changes

2021-06-23 02:44 UTC, merged